# This is a basic workflow to help you get started with Actions

name: daily GKD!

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  schedule:
    - cron: '0 11 * * *'
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  GKD:
    name: daily GKD!
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout code
        uses: actions/checkout@v2

      - name: variable
        id: variable
        run: |
          echo ::set-output name=LAST_USERNAME::$(git log -1 --pretty=format:'%an' | xargs)
          echo ::set-output name=LAST_EMAIL::$(git log -1 --pretty=format:'%ae' | xargs)
      - name: git operations
        run: |
          git config --global user.name "${{steps.variable.outputs.LAST_USERNAME}}"
          git config --global user.email "${{steps.variable.outputs.LAST_EMAIL}}"
      - name: run script
        run: |
          chmod +x ./commit.sh
          echo "$(expr $(date +%s) - 86402)" > ./begin.date
          ./commit.sh

      - name: git operations
        run: git push --set-upstream origin main